#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Miguel Xochicale

#markdown: kramdown
permalink: /blog/:year/:month/:day/:title
